name:                space-station15
version:             0.1.0.0
github:              "Eucalyptus214/space-station-15"
license:             MIT
author:              "Eucalyptus"
maintainer:          "execute@erisws.com"
copyright:           "2024 Eucalyptus"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Eucalyptus214/space-station-15#readme>

dependencies:
- base >= 4.2 && < 5
- random
- template-haskell
- exceptions
- sdl2
- apecs
- network
- network-udp
- containers
- directory
- OpenAL
- OpenGL
- transformers
- HDBC
- HDBC-sqlite3
- GLUT
- conversion
- mono-traversable
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  space-station15-client:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - space-station15
  space-station15-server:
    main:               Main.hs
    source-dirs:        server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - space-station15
